server:
  port: 8888
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres_db:5432/pgk
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  mail:
    host: smtp.rambler.ru
    username:
    password:
    port: 465
    protocol: smtps
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  redis:
    host: localhost
    port: 6379
jwt:
  accessToken: "qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w=="
  refreshToken: "qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w=="
upload:
  path: /home/badma/Документы/Hackaton2022/pgk
