server:
  port: 8888
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres_db:5432/wereL
    username: root
    password: root
  jackson:
    deserialization.accept-single-value-as-array: true

  jpa:
    show-sql: true
    hibernate:
      show_sql: true
      ddl-auto: none
      cache.use.query_cache: false
      cache.use_second_level_cache: false
  mail:
    host: smtp.rambler.ru
    username: badma_a1qa@rambler.ru
    password: A1qa2022!
    port: 465
    protocol: smtps
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  redis:
    host: redis
    port: 6379
jwt:
  accessToken: "qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w=="
  refreshToken: "qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w=="
